version: '3'
services:
  application:
    image: backend:latest
    restart: always
    ports:
      - "8000:8080"
  datbase:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_management_system
      MYSQL_USER: chinna
      MYSQL_PASSWORD: root
    restart: always
    ports:
      - "3306:3306"
  Frontend:
    image: frontend:latest
    restart: always
    ports:
      - "80:3000"
