version: '3'
services:
  application:
    image: myapp:latest
    restart: always
    ports:
      - "8080:8080"
  datbase: mysql
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
